on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.12.2
      - run: mix deps.get
      - run: mix test
